DROP TABLE IF EXISTS ACCOUNTS;
CREATE TABLE ACCOUNTS (
    CUSTOMER_NUMBER VARCHAR(8),
    CUSTOMER_ACCOUNT VARCHAR(10),
    PRODUCT_NUMBER INT,
    PRODUCT_NAME VARCHAR(10),
    STATUS VARCHAR(10),
    BALANCE  DECIMAL(10,2),
    CREATION_DATE VARCHAR(10),
    PRIMARY KEY (CUSTOMER_NUMBER, CUSTOMER_ACCOUNT));